fontomas:
  max_glyphs: 100
  glyph_size:
    min: 8    # minimal size
    val: 16   # default size
    max: 32   # miximum size
locales:
  enabled: [en]
  default: en
listen:
  host: localhost
  port: 3000
