router:
  map:
    fontello.app:
      "/({id})":
        id: /[0-9a-f]{24}/
      "/#search={search}":
        search: /\S+/

    fontello.font.download:
      "/download/{file}":
        file: /.+/

    core.assets:
      "/assets/{path}":
        path: /.+/
        responder: bin

    core.static:
      "/{file}":
        file: /favicon.ico|robots.txt|snippet.png|fuckup.log/
        responder: bin
