router:
  map:
    app:
      "/": ~
    font.download:
      "/download/{file}":
        file: /.+/
    assets:
      "/assets/{path}":
        path: /.+/
    static:
      "/{file}":
        file: /favicon.ico|robots.txt|snippet.png|fuckup.log/
